### ISSUE TITLE
An example with graphics using Nim's js backend

### ISSUE THREAD

**Issue by pietroppeter** [EriKWDev/easyess#2]
hi, this weekend I enjoyed playing with this library (nice work!) and made a small bouncing balls demo.
I thought you might be interested in knowing that your library works with js backend: https://pietroppeter.github.io/nblog/drafts/easyess_js_ball.html

Have a great week!

**Comment by EriKWDev** [comment]
Hey awesome! Thanks for sharing! It made me really happy to see my toy project being written about xP

I've not personally ever compiled Nim to js, but awesome that easyess works there as well!
